export const sampleStudents = [
  ["01", "陳大文", "Chan Tai Man", "男"],
  ["02", "李小華", "Lee Siu Wah", "女", ""],
  ["03", "張建國", "Benny Cheung", "男"],
  ["04", "黃美麗", "Mary Wong", "女", ""],
  ["05", "何家朗", "Alan Ho", "男", ""],
  ["06", "梁詠欣", "Yan Leung", "女", ""],
  ["07", "趙俊熙", "Justin Chiu", "男"],
  ["08", "周善妍", "Sonia Chow", "女", ""],
  ["09", "林子軒", "Carson Lam", "男", ""],
  ["10", "劉芷晴", "Jenny Lau", "女", ""],
  ["11", "吳卓言", "Derek Ng", "男", ""],
  ["12", "葉曉彤", "Hannah Yip", "女", ""],
  ["13", "鄭文軒", "Jason Cheng", "男"],
  ["14", "馮樂怡", "Joyce Fung", "女", ""],
  ["15", "蘇嘉朗", "Kelvin So", "男", ""],
  ["16", "郭穎欣", "Winnie Kwok", "女", ""],
  ["17", "馬俊賢", "Marcus Ma", "男", ""],
  ["18", "方芷妍", "Cindy Fong", "女", ""],
  ["19", "葉子健", "Brian Yip", "男", ""],
  ["20", "蔡詠琳", "Kelly Choi", "女"],
  ["21", "曾志謙", "Martin Tsang", "男", ""],
  ["22", "潘昕南", "Nathan Poon", "男", ""],
  ["23", "鄧嘉怡", "Karen Tang", "女", ""],
  ["24", "何穎彤", "Natalie Ho", "女", ""],
  ["25", "沈楚進", "Jun Shum", "男", ""],
  ["26", "宋曜君", "Kwin Sung", "男"],
  ["27", "鄧灝翹", "Curtis Tang", "男", ""],
  ["28", "曾至晴", "Teo Tsang", "女", ""],
  ["29", "曾康睿", "Daniel Tsang", "男", ""],
  ["30", "黃愷晴", "Haze Wong", "女", ""],
  ["31", "黃甘兒", "Navedia Wong", "女", ""],
  ["32", "謝其益", "Manfred Tse", "男"],
  ["33", "張雅洛", "Yinna Cheung", "女", ""],
  ["34", "廖少媛", "Newa Liu", "女"],
].map(([number, chineseName, englishName, gender], index) => ({
  id: `student-${index + 1}`,
  number,
  chineseName,
  englishName,
  gender,
  tags: [],
  className: "2D",
}));
